# References {.unnumbered}

## Key MoBPS Publications

**Main Paper:**

Pook, T., Freudenthal, J., Korte, A., & Simianer, H. (2020). Using local convolutional neural networks for genomic prediction. *Frontiers in Genetics*, 11, 561497 [@pook2020lcnn].

Pook, T., Schlather, M., & Simianer, H. (2020). MoBPS - Modular Breeding Program Simulator. *G3: Genes, Genomes, Genetics*, 10(6), 1915-1918 [@pook2020mobps].

## Additional Resources

- **GitHub Repository:** <https://github.com/tpook92/MoBPS>
- **Web Interface:** <https://www.mobps.de>
- **CRAN Page:** <https://CRAN.R-project.org/package=MoBPS>

## Contact

For questions, bug reports, or collaborations:

- **Torsten Pook:** [Torsten.pook@wur.nl](mailto:Torsten.pook@wur.nl)
- Wageningen University & Research
- Animal Breeding and Genomics Group

## Citation

If you use MoBPS in your research, please cite the main paper [@pook2020mobps]:

```
@article{pook2020mobps,
  title={MoBPS—Modular breeding program simulator},
  author={Pook, Torsten and Schlather, Martin and Simianer, Henner},
  journal={G3: Genes, Genomes, Genetics},
  volume={10},
  number={6},
  pages={1915--1918},
  year={2020},
  publisher={Oxford University Press},
  doi={10.1534/g3.120.401193},
  url={https://doi.org/10.1534/g3.120.401193}
}
```

## Related Software

- **AlphaSimR:** Another breeding simulation package
- **QMSim:** Quantitative and molecular simulation
- **Genomic Selection packages:** rrBLUP, BGLR, sommer, BLUPF90

